#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")"

echo "==> Building WASM with SIMD..."
RUSTFLAGS="-C target-feature=+simd128 -C link-args=-zstack-size=16384" \
  cargo build --target wasm32-unknown-unknown --release

WASM_IN="target/wasm32-unknown-unknown/release/spliterator_wasm.wasm"
WASM_OUT="spliterator_wasm.wasm"

if command -v wasm-opt >/dev/null 2>&1; then
  echo "==> Optimizing with wasm-opt..."
  wasm-opt -Oz --enable-simd "$WASM_IN" -o "$WASM_OUT"
else
  echo "==> wasm-opt not found; shipping the cargo output as-is (a few hundred bytes larger)."
  echo "    Install it (e.g. \`cargo install wasm-opt\`) and re-run for the size-optimized artifact."
  cp "$WASM_IN" "$WASM_OUT"
fi

echo "==> Base64 encoding..."
# Strip newlines so the constant stays a single-line string literal. GNU base64 wraps at
# 76 columns by default and macOS base64 does not, so normalize across both with `tr`.
BASE64=$(base64 < "$WASM_OUT" | tr -d '\n')

echo "==> Writing TypeScript constant to lib/wasm_base64.ts..."
cat > ../lib/wasm_base64.ts << TSEOF
/**
 * @copyright Sister Software
 * @license MIT
 * @author Teffen Ellis, et al.
 * Base64-encoded WASM module for SIMD-accelerated delimiter scanning.
 * Generated by wasm/build.sh — do not edit by hand.
 * The module exports:
 *   - memory: WebAssembly.Memory (1 page = 64KB initial, grows on demand, no fixed maximum)
 *   - find_delimiter(haystack_offset, haystack_len, pattern_offset, pattern_len) → i32
 *     Returns the byte offset of the first match, or -1.
 *   - find_all_delimiters(haystack_offset, haystack_len, pattern_offset, pattern_len,
 *                         results_offset, max_results) → usize
 *     Writes (start, end) i32 pairs to results_offset, returns count.
 */
export const WASM_BASE64 =
	"${BASE64}"
TSEOF

echo "==> Done. WASM size: $(wc -c < "$WASM_OUT") bytes, base64: ${#BASE64} chars"
