#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")"

echo "==> Building WASM with SIMD..."
RUSTFLAGS="-C target-feature=+simd128 -C link-args=-zstack-size=16384" \
  cargo build --target wasm32-unknown-unknown --release

WASM_IN="target/wasm32-unknown-unknown/release/spliterator_wasm.wasm"
WASM_OUT="spliterator_wasm.wasm"

echo "==> Optimizing with wasm-opt..."
wasm-opt -Oz --enable-simd "$WASM_IN" -o "$WASM_OUT"

echo "==> Base64 encoding..."
BASE64=$(base64 -i "$WASM_OUT")

echo "==> Writing TypeScript constant to lib/wasm_base64.ts..."
cat > ../lib/wasm_base64.ts << TSEOF
/**
 * Base64-encoded WASM module for SIMD-accelerated delimiter scanning.
 *
 * Generated by wasm/build.sh — do not edit by hand.
 *
 * The module exports:
 *   - memory: WebAssembly.Memory (1 page = 64KB initial, 256 pages max = 16MB)
 *   - find_delimiter(haystack_offset, haystack_len, pattern_offset, pattern_len) → i32
 *     Returns the byte offset of the first match, or -1.
 *   - find_all_delimiters(haystack_offset, haystack_len, pattern_offset, pattern_len,
 *                         results_offset, max_results) → usize
 *     Writes (start, end) i32 pairs to results_offset, returns count.
 */
export const WASM_BASE64 = "${BASE64}"
TSEOF

echo "==> Done. WASM size: $(wc -c < "$WASM_OUT") bytes, base64: ${#BASE64} chars"
