#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")"

echo "==> Building WASM with SIMD..."
RUSTFLAGS="-C target-feature=+simd128 -C link-args=-zstack-size=16384" \
  cargo build --target wasm32-unknown-unknown --release

WASM_IN="target/wasm32-unknown-unknown/release/spliterator_wasm.wasm"
WASM_OUT="spliterator_wasm.wasm"

if command -v wasm-opt >/dev/null 2>&1; then
  echo "==> Optimizing with wasm-opt..."
  wasm-opt -Oz --enable-simd "$WASM_IN" -o "$WASM_OUT"
else
  echo "==> wasm-opt not found; shipping the cargo output as-is (a few hundred bytes larger)."
  echo "    Install it (e.g. \`cargo install wasm-opt\`) and re-run for the size-optimized artifact."
  cp "$WASM_IN" "$WASM_OUT"
fi

echo "==> Base64 encoding..."
# Strip newlines so the constant stays a single-line string literal. GNU base64 wraps at
# 76 columns by default and macOS base64 does not, so normalize across both with `tr`.
BASE64=$(base64 < "$WASM_OUT" | tr -d '\n')

echo "==> Writing TypeScript constant to lib/core/wasm_base64.ts..."
cat > ../lib/core/wasm_base64.ts << TSEOF
/**
 * @license MIT
 * @author Teffen Ellis, et al.
 * @copyright Sister Software
 *
 * Auto-generated by wasm/build.sh. Do not edit.
 */

/**
 * Base64 WASM for fast delimiter scanning.
 *
 * Exports:
 *
 * - Memory: WebAssembly.Memory (starts at 64KB, can grow)
 * - \`find_delimiter(...) -> i32 (first match offset or -1)\`
 * - \`find_all_delimiters(...) -> usize ((start, end) pairs)\`
 * - \`find_all_matches(...) -> usize ((offset, pattern_id) pairs)\`
 * - \`scan_delimited_ranges(...) -> usize (resumable ranges)\`
 * - \`scan_csv_cells(...) -> usize (UTF-16 cell boundaries)\`
 */
export const WASM_BASE64 =
	"${BASE64}"
TSEOF

echo "==> Done. WASM size: $(wc -c < "$WASM_OUT") bytes, base64: ${#BASE64} chars"
