/**
 * @copyright Sister Software
 * @license MIT
 * @author Teffen Ellis, et al.
 */

import { mkdtemp, readFile, rm } from "node:fs/promises"
import { tmpdir } from "node:os"
import { join } from "node:path"

import { type AsyncSequence, XLSXSpliterator } from "spliterator"
import { afterAll, beforeAll, expectTypeOf, test } from "vitest"
import writeXlsxFile, { type SheetData } from "write-excel-file/node"

// The fixture is generated by `write-excel-file` itself — the vendor library, not our writer —
// so reader tests do not depend on the writer under test.
let fixtureDirectory: string
let fixturePath: string

const joined = new Date(Date.UTC(2020, 0, 2))

interface TypedXLSXRow {
	full_name: string
	score: number
	active: boolean
	joined: Date | null
}

const mainSheetRows = [
	["Full Name", "Score", "Active", "Joined"],
	["Ada", 42, true, joined],
	["Grace", 3.5, false, null],
	["Linus", 7, true, null],
] as const

const extrasSheetRows = [
	["Key", "Value"],
	["answer", 42],
] as const

function toVendorSheetData(rows: ReadonlyArray<ReadonlyArray<string | number | boolean | Date | null>>): SheetData {
	return rows.map((row) =>
		row.map((value) => {
			if (value instanceof Date) {
				return { value, format: "yyyy-mm-dd" }
			}

			return value
		})
	)
}

beforeAll(async () => {
	fixtureDirectory = await mkdtemp(join(tmpdir(), "spliterator-xlsx-"))
	fixturePath = join(fixtureDirectory, "fixture.xlsx")

	await writeXlsxFile([
		{ data: toVendorSheetData(mainSheetRows), sheet: "Main" },
		{ data: toVendorSheetData(extrasSheetRows), sheet: "Extras" },
	]).toFile(fixturePath)
})

afterAll(async () => {
	await rm(fixtureDirectory, { recursive: true, force: true })
})

test("`from` throws, directing callers to `fromAsync`", ({ expect }) => {
	expect(() => XLSXSpliterator.from()).toThrowError(TypeError)
	expect(() => XLSXSpliterator.from()).toThrowError(/fromAsync/)
})

test("Instantiation throws", ({ expect }) => {
	// @ts-expect-error Static class must not be constructable.
	expect(() => new XLSXSpliterator()).toThrowError(TypeError)
})

test("Rows emit as arrays of typed cells, header consumed by default", async ({ expect }) => {
	const rows = await XLSXSpliterator.fromAsync(fixturePath).toArray()

	expect(rows).toEqual([
		["Ada", 42, true, joined],
		["Grace", 3.5, false, null],
		["Linus", 7, true, null],
	])
})

test("Rows emit as records with normalized keys", async ({ expect }) => {
	const records = XLSXSpliterator.fromAsync<TypedXLSXRow>(fixturePath, { mode: "object" })

	expectTypeOf(records).toEqualTypeOf<AsyncSequence<TypedXLSXRow>>()

	const rows = await records.toArray()

	expect(rows).toEqual([
		{ full_name: "Ada", score: 42, active: true, joined },
		{ full_name: "Grace", score: 3.5, active: false, joined: null },
		{ full_name: "Linus", score: 7, active: true, joined: null },
	])
})

test("Header normalization can be disabled", async ({ expect }) => {
	const rows = await XLSXSpliterator.fromAsync(fixturePath, { mode: "object", normalizeKeys: false }).toArray()

	expect(Object.keys(rows[0]!)).toEqual(["Full Name", "Score", "Active", "Joined"])
})

test("Rows emit as entries", async ({ expect }) => {
	const rows = await XLSXSpliterator.fromAsync(fixturePath, { mode: "entries", take: 1 }).toArray()

	expect(rows).toEqual([
		[
			["full_name", "Ada", 0],
			["score", 42, 1],
			["active", true, 2],
			["joined", joined, 3],
		],
	])
})

test("`header: false` yields the header row as data", async ({ expect }) => {
	const rows = await XLSXSpliterator.fromAsync(fixturePath, { header: false, take: 1 }).toArray()

	expect(rows).toEqual([["Full Name", "Score", "Active", "Joined"]])
})

test("Sheet selection by name and by number", async ({ expect }) => {
	const byName = await XLSXSpliterator.fromAsync(fixturePath, { sheet: "Extras", mode: "object" }).toArray()

	expect(byName).toEqual([{ key: "answer", value: 42 }])

	const byNumber = await XLSXSpliterator.fromAsync(fixturePath, { sheet: 2 }).toArray()

	expect(byNumber).toEqual([["answer", 42]])
})

test("Unknown sheet propagates the vendor error", async ({ expect }) => {
	await expect(XLSXSpliterator.fromAsync(fixturePath, { sheet: "Nope" }).toArray()).rejects.toThrowError()
})

test("`drop` and `take` bound the emitted rows", async ({ expect }) => {
	const rows = await XLSXSpliterator.fromAsync(fixturePath, { drop: 1, take: 1 }).toArray()

	expect(rows).toEqual([["Grace", 3.5, false, null]])
})

test("Transformers receive typed cell values", async ({ expect }) => {
	const seen: unknown[] = []

	const rows = await XLSXSpliterator.fromAsync(fixturePath, {
		mode: "object",
		take: 1,
		transformers: {
			joined: (value) => {
				seen.push(value)

				return value instanceof Date ? value.toISOString() : value
			},
		},
	}).toArray()

	expect(seen[0]).toBeInstanceOf(Date)
	expect(rows[0]!.joined).toBe(joined.toISOString())
})

test("Reads from an in-memory byte source", async ({ expect }) => {
	const bytes = new Uint8Array(await readFile(fixturePath))

	const rows = await XLSXSpliterator.fromAsync(bytes, { mode: "object", take: 1 }).toArray()

	expect(rows).toEqual([{ full_name: "Ada", score: 42, active: true, joined }])
})

//#region Writer

test("Write: record rows round-trip through the reader", async ({ expect }) => {
	const records = [
		{ name: "Ada", score: 42, active: true },
		{ name: "Grace", score: 3.5, active: false },
	]

	const outputPath = join(fixtureDirectory, "written-records.xlsx")

	await XLSXSpliterator.write(records).toFile(outputPath)

	const rows = await XLSXSpliterator.fromAsync(outputPath, { mode: "object" }).toArray()

	expect(rows).toEqual(records)
})

test("Write: accepts an async iterable, composing with AsyncSequence pipelines", async ({ expect }) => {
	const source = XLSXSpliterator.fromAsync(fixturePath, { mode: "object" }).map((row) => ({
		full_name: row.full_name,
		score: typeof row.score === "number" ? row.score * 10 : row.score,
	}))

	const buffer = await XLSXSpliterator.write(source).toBuffer()
	const rows = await XLSXSpliterator.fromAsync(new Uint8Array(buffer), { mode: "object" }).toArray()

	expect(rows).toEqual([
		{ full_name: "Ada", score: 420 },
		{ full_name: "Grace", score: 35 },
		{ full_name: "Linus", score: 70 },
	])
})

test("Write: array rows write headerless", async ({ expect }) => {
	const outputPath = join(fixtureDirectory, "written-arrays.xlsx")

	await XLSXSpliterator.write(
		[
			["a", 1],
			["b", 2],
		],
		{ sheet: "Letters" }
	).toFile(outputPath)

	const rows = await XLSXSpliterator.fromAsync(outputPath, { header: false, sheet: "Letters" }).toArray()

	expect(rows).toEqual([
		["a", 1],
		["b", 2],
	])
})

test("Write: missing record keys become null cells", async ({ expect }) => {
	const buffer = await XLSXSpliterator.write([{ a: 1, b: 2 }, { a: 3 }]).toBuffer()

	const rows = await XLSXSpliterator.fromAsync(new Uint8Array(buffer)).toArray()

	expect(rows).toEqual([
		[1, 2],
		[3, null],
	])
})

test("Write: `header: false` suppresses the derived header row", async ({ expect }) => {
	const buffer = await XLSXSpliterator.write([{ a: 1, b: 2 }], { header: false }).toBuffer()

	const rows = await XLSXSpliterator.fromAsync(new Uint8Array(buffer), { header: false }).toArray()

	expect(rows).toEqual([[1, 2]])
})

test("Write: `header: true` with array rows throws", async ({ expect }) => {
	await expect(XLSXSpliterator.write([["a", 1]], { header: true }).toBuffer()).rejects.toThrowError(TypeError)
})

//#endregion Writer
